[build_system]
requires = ['setuptools>=42.0', "wheel"]
bulid-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
testpath =[
    "tests"
]

[tool.mypy]
mypy_path="src"
ignore_missing_imports = true